tags:
  - Role Settings
summary: Mendapatkan seluruh data setting dan value setiap role berdasarkan Role ID dan Type
description: |
  Endpoint ini digunakan untuk mengambil list seluruh setting dan value per role dan tipe yang tersedia. Hanya dapat diakses oleh admin.
  - Membutuhkan parameter **Role ID dan Type di Path**  untuk memfilter setting berdasarkan role dan type.
  - Jika suatu setting belum memiliki value untuk role tersebut, maka value akan diisi dengan default dari table settings.
security:
  - bearerAuth: []
parameters:
  - name: role_id
    in: path
    required: true
    schema:
      type: string
      format: uuid
    description: ID dari role yang akan diambil setting-nya
  - name: type
    in: path
    required: true
    schema:
      type: string
    description: Tipe dari setting yang akan diambil (contoh feature, general, dll)
responses:
  200:
    description: Berhasil mengambil list role settings
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
              example: Berhasil mengambil List settings
            data:
              type: array
              items:
                type: object
                properties:
                  role_id:
                    type: string
                    format: uuid
                    example: 2d328885-d408-4926-bc4f-785dcf32cd02
                  setting_id:
                    type: string
                    format: uuid
                    example: f2682f69-e968-4b56-975e-5be72c461415
                  type:
                    type: string
                    example: general/feature
                  data_type:
                    type: string
                    example: string/integer/boolean/array/object
                  name:
                    type: string
                    example: Chat topic expired days
                  description:
                    type: string
                    example: Batas max chat topic auto delete, dilihat dari last date chat per topic
                  unit:
                    type: string
                    nullable: true
                    example: days
                  value:
                    oneOf:
                      - type: string
                      - type: integer
                      - type: boolean
                      - type: array
                      - type: object
                    example: 500
  401:
    description: Tidak terautentikasi / token tidak valid
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
              example: Unauthorized
  403:
    description: Tidak memiliki akses admin
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
              example: Access tidak diizinkan
  500:
    description: Gagal mengambil list role settings
    content:
      application/json:
        schema:
          type: object
          properties:
            error:
              type: string
              example: Gagal mengambil list setting
